repositories:
    - name: dts
      url: https://helm.dts-stn.com
    # helm-git powered repository: You can treat any Git repository as a charts repository
    - name: qps
      url: git+https://{{ requiredEnv "GITHUB_USER" }}:{{ requiredEnv "GITHUB_TOKEN" }}@github.com/DTS-STN/question-priority-service@helm/charts?ref=development
{{- if or (eq .Environment.Name "prod-blue") (eq .Environment.Name "prod-green") }}    
context: EsDCDTSRG-K8S
{{ else }}
context: EsDCDTSDevRG-K8S
{{ end }}
   
environments:
    dev:
    prod-blue:
    prod-green: 

releases:
# Question Priority Service
  - name: qps-{{ .Environment.Name }}
    chart: qps/question-priority-service
    version: 0.0.3
    values:
      - overrides/qps.yaml.gotmpl
    labels:
        category: dts
        app: qps
        tier: server
    namespace: qps-{{ .Environment.Name }}
    installed: true
    wait: false
    force: false
