// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthcheck": {
            "get": {
                "description": "Returns Healthy",
                "summary": "Returns Healthy",
                "operationId": "healthcheck",
                "responses": {
                    "200": {
                        "description": "Healthy",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/next": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Request Prioritized Questions",
                "operationId": "next-question",
                "parameters": [
                    {
                        "description": "Journey 1",
                        "name": "NextQuestion",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/bindings.NextQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/renderings.NextQuestionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/renderings.QPSError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/renderings.QPSError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/renderings.QPSError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "benefits.Benefit": {
            "type": "object",
            "properties": {
                "eligible": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "bindings.NextQuestionRequest": {
            "type": "object",
            "properties": {
                "benefit_list": {
                    "description": "Array of specific benefits to get the questions for",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "life_journeys": {
                    "description": "Array of life journeys, which represent a subset of benefits",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "question_list": {
                    "description": "List of answered priority questions",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Question"
                    }
                },
                "request_date": {
                    "description": "Date period for request in ms since epoch",
                    "type": "integer"
                }
            }
        },
        "models.Question": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "renderings.NextQuestionResponse": {
            "type": "object",
            "properties": {
                "benefit_eligibility": {
                    "description": "List of eligible and non-eligible benefits, populated as responses to\nprioritized questions are received",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/benefits.Benefit"
                    }
                },
                "question_list": {
                    "description": "List of answered priority questions with their answers and the next priority\nquestion with a value of null",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Question"
                    }
                },
                "request_date": {
                    "description": "Date period for request in ms since epoch",
                    "type": "integer"
                }
            }
        },
        "renderings.QPSError": {
            "type": "object",
            "properties": {
                "error_code": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Question Prioritization Service",
	Description: "This is a service to return questions that when answered will return elegible benefits.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
