basePath: /
definitions:
  bindings.NextQuestionRequest:
    properties:
      key:
        type: string
    type: object
  renderings.NextQuestionResponse:
    properties:
      key:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a service to return questions that when answered will return
    elegible benefits.
  title: Question Prioritization Service
  version: "1.0"
paths:
  /healthcheck:
    get:
      description: Returns Healthy
      operationId: healthcheck
      responses:
        "200":
          description: Healthy
          schema:
            type: string
      summary: Returns Healthy
  /next:
    post:
      consumes:
      - application/json
      operationId: next-question
      parameters:
      - description: value
        in: body
        name: NextQuestion
        required: true
        schema:
          $ref: '#/definitions/bindings.NextQuestionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/renderings.NextQuestionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/renderings.NextQuestionResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/renderings.NextQuestionResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/renderings.NextQuestionResponse'
      summary: Request Prioritized Questions
swagger: "2.0"
