basePath: /
definitions:
  benefits.Benefit:
    properties:
      eligible:
        type: boolean
      id:
        type: string
    type: object
  bindings.NextQuestionRequest:
    properties:
      benefit_list:
        description: Array of specific benefits to get the questions for
        items:
          type: string
        type: array
      life_journeys:
        description: Array of life journeys, which represent a subset of benefits
        items:
          type: string
        type: array
      question_list:
        description: List of answered priority questions
        items:
          $ref: '#/definitions/models.Question'
        type: array
      request_date:
        description: Date period for request in ms since epoch
        type: integer
    type: object
  models.Question:
    properties:
      answer:
        type: string
      id:
        type: string
    type: object
  renderings.NextQuestionResponse:
    properties:
      benefit_eligibility:
        description: |-
          List of eligible and non-eligible benefits, populated as responses to
          prioritized questions are received
        items:
          $ref: '#/definitions/benefits.Benefit'
        type: array
      question_list:
        description: |-
          List of answered priority questions with their answers and the next priority
          question with a value of null
        items:
          $ref: '#/definitions/models.Question'
        type: array
      request_date:
        description: Date period for request in ms since epoch
        type: integer
    type: object
  renderings.QPSError:
    properties:
      error_code:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a service to return questions that when answered will return
    elegible benefits.
  title: Question Prioritization Service
  version: "1.0"
paths:
  /healthcheck:
    get:
      description: Returns Healthy
      operationId: healthcheck
      responses:
        "200":
          description: Healthy
          schema:
            type: string
      summary: Returns Healthy
  /next:
    post:
      consumes:
      - application/json
      operationId: next-question
      parameters:
      - description: Journey 1
        in: body
        name: NextQuestion
        schema:
          $ref: '#/definitions/bindings.NextQuestionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/renderings.NextQuestionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/renderings.QPSError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/renderings.QPSError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/renderings.QPSError'
      summary: Request Prioritized Questions
swagger: "2.0"
